val_g =   9.81;            % gravity [N/kg]
val_L = 0.111;             % distance of the pendulum's center of mass [m] (INVENTOR)
val_D = 0.245;             % distance between the wheels [m]
val_r = 0.045;             % wheel radius [m]
val_J_v_x = 26653*1e-6;    % principal moment of inertia of the platform, x-axis [kg m^2] (INVENTOR)
val_J_v_y = 22632*1e-6;    % principal moment of inertia of the platform, y-axis [kg m^2] (INVENTOR)
val_J_v_z = 7631*1e-6;     % principal moment of inertia of the platform, z-axis [kg m^2] (INVENTOR)
val_m_v = 1.740;           % mass of the platform [kg] (INVENTOR)
val_J_w_xz = 16*1e-6;      % principal moment of inertia of the wheel, x/z-axis [kg m^2] (INVENTOR)
val_J_w_y = 33*1e-6;       % principal moment of inertia of the wheel, y-axis [kg m^2] (INVENTOR)
val_m_w = 0.035;           % mass of the wheel + adapter, shaft and gears estimated [kg]
val_b_Coul_R = 0.1;        % Coulomb friction [Nm] (FOR ESTIMATE)
val_b_visc_R = 0.01;       % viscous friction [Nms/rad] (FOR ESTIMATE)
val_b_Coul_L = 0.1;        % Coulomb friction [Nm] (FOR ESTIMATE)
val_b_visc_L = 0.01;       % viscous friction [Nms/rad] (FOR ESTIMATE)
val_R = 2.22;              % motor resistance [Ω]
val_k_e = 0.56;            % electric constant [Vs/rad]
val_k_m = 0.39;            % mechanical constant [Nm/A]
val_L_m = 0.0023;          % inductance of the motor coil - Pololu forum [H]

Params(1) = val_g;
Params(2) = val_L;
Params(3) = val_D;
Params(4) = val_r;
Params(5) = val_J_v_x;
Params(6) = val_J_v_y;
Params(7) = val_J_v_z;
Params(8) = val_m_v;
Params(9) = val_J_w_xz;
Params(10) = val_J_w_y;
Params(11) = val_m_w;
Params(12) = val_b_Coul_R;
Params(13) = val_b_visc_R;
Params(14) = val_b_Coul_L;
Params(15) = val_b_visc_L;
Params(16) = val_R;
Params(17) = val_k_e;
Params(18) = val_k_m;
Params(19) = val_L_m;
